name: analog_clock
description: Awarded steampunk like, analog clock for Flutter Clock contest.
version: 1.0.0+1
repository: https://github.com/tsinis/flutter_clock
issue_tracker: https://github.com/tsinis/flutter_clock/issues
maintainer: Roman Cinis
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  clock: ^1.1.0
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper

dev_dependencies:

  dart_code_metrics: ^4.13.0
  flutter_test:
    sdk: flutter
  linter: ^1.21.2


flutter:
  uses-material-design: true

  assets:
    - assets/FlutterClock.flr